Add two more function patches and automatic testing mechanism
Adds strcpy and strchr patches. Also running `make check` runs a very
simple testsuite.

Signed-off-by: Giuliano Belinassi <gbelinassi@suse.de>

diff --git a/common/Makefile.common b/common/Makefile.common
--- a/common/Makefile.common
+++ b/common/Makefile.common
@@ -22,6 +22,36 @@ $(LP_FUNC)_livepatch1.so:$(LP_FUNC)_livepatch1.o $(LP_FUNC)_livepatch1.dsc
 %.o: %.c
 	$(CC) $(CFLAGS) -c -o $@ $^
 
-.PHONY: clean
+.PHONY: clean check
 clean:
 	rm -rf test *.o *.so *.dsc
+
+.ONESHELL:
+check: test $(LP_FUNC)_livepatch1.so
+	@LIBPULP_PATH=/usr/local/lib64/libpulp.so; \
+	if [ ! -f "$${LIBPULP_PATH}" ]; then \
+		LIBPULP_PATH=/usr/lib64/libpulp.so; \
+	fi; \
+	if [ ! -f "$${LIBPULP_PATH}" ]; then \
+		LIBPULP_PATH=/lib64/libpulp.so; \
+	fi; \
+	if [ ! -f "$${LIBPULP_PATH}" ]; then \
+		echo "ERROR: libpulp not found"; \
+		exit 1; \
+	fi; \
+	\
+	LD_PRELOAD=$${LIBPULP_PATH} ./test > /dev/null &
+	pid=$$! ; \
+	sleep 0.1; \
+	ulp trigger -q -p $${pid} $(LP_FUNC)_livepatch1.so; \
+	if [ $$? -ne 0 ]; then \
+		echo "ERROR: Test failure"; \
+	fi; \
+	kill -s 10 $${pid}; \
+	wait $${pid}; \
+	if [ $$? -ne 0 ]; then \
+		echo "FAIL: $(word 2,$^)"; \
+		exit 1; \
+	fi; \
+	echo "SUCCESS: $(word 2,$^)";
+
